version: '2.1'

services:
  #service 1: mysql database image creation
  db:
    image: mysql:5.6.17
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=spring
    ports:
      - "3307:3307"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


  # service 2: User Manager app image creation
  userservice:
    image: user-service
    container_name: user-service-app     # name of container created from image
    build:
      context: .                          # path to docker file
      dockerfile: DockerFile              # docker file name
    ports:
      - "8090:8080"                       # stock service port
    restart: always

    depends_on:                           #define dependencies of this app
      db :                              #dependency name (which is defined with this name 'db' in this file earlier)
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3307/user_manager?createDatabaseIfNotExist=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: spring